/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'Main_Soc' in SOPC Builder design 'final_soc'
 * SOPC Builder design path: ../../final_soc.sopcinfo
 *
 * Generated: Mon Jan 03 20:07:46 CST 2022
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_gen2"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x00014820
#define ALT_CPU_CPU_ARCH_NIOS2_R1
#define ALT_CPU_CPU_FREQ 50000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "tiny"
#define ALT_CPU_DATA_ADDR_WIDTH 0x1d
#define ALT_CPU_DCACHE_LINE_SIZE 0
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_DCACHE_SIZE 0
#define ALT_CPU_EXCEPTION_ADDR 0x00020020
#define ALT_CPU_FLASH_ACCELERATOR_LINES 0
#define ALT_CPU_FLASH_ACCELERATOR_LINE_SIZE 0
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 50000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 0
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 0
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_ICACHE_SIZE 0
#define ALT_CPU_INST_ADDR_WIDTH 0x1d
#define ALT_CPU_NAME "Main_Soc"
#define ALT_CPU_OCI_VERSION 1
#define ALT_CPU_RESET_ADDR 0x00020000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x00014820
#define NIOS2_CPU_ARCH_NIOS2_R1
#define NIOS2_CPU_FREQ 50000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "tiny"
#define NIOS2_DATA_ADDR_WIDTH 0x1d
#define NIOS2_DCACHE_LINE_SIZE 0
#define NIOS2_DCACHE_LINE_SIZE_LOG2 0
#define NIOS2_DCACHE_SIZE 0
#define NIOS2_EXCEPTION_ADDR 0x00020020
#define NIOS2_FLASH_ACCELERATOR_LINES 0
#define NIOS2_FLASH_ACCELERATOR_LINE_SIZE 0
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 0
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 0
#define NIOS2_ICACHE_LINE_SIZE_LOG2 0
#define NIOS2_ICACHE_SIZE 0
#define NIOS2_INST_ADDR_WIDTH 0x1d
#define NIOS2_OCI_VERSION 1
#define NIOS2_RESET_ADDR 0x00020000


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_NEW_SDRAM_CONTROLLER
#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_SGDMA
#define __ALTERA_AVALON_SYSID_QSYS
#define __ALTERA_NIOS2_GEN2
#define __ALTPLL
#define __PLAYER_CONTROLLER
#define __SRAM_DUAL_CONTROLLER


/*
 * Main_Soc_onchip_mem_for_Tiles configuration
 *
 */

#define ALT_MODULE_CLASS_Main_Soc_onchip_mem_for_Tiles altera_avalon_onchip_memory2
#define MAIN_SOC_ONCHIP_MEM_FOR_TILES_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define MAIN_SOC_ONCHIP_MEM_FOR_TILES_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define MAIN_SOC_ONCHIP_MEM_FOR_TILES_BASE 0x30000
#define MAIN_SOC_ONCHIP_MEM_FOR_TILES_CONTENTS_INFO ""
#define MAIN_SOC_ONCHIP_MEM_FOR_TILES_DUAL_PORT 0
#define MAIN_SOC_ONCHIP_MEM_FOR_TILES_GUI_RAM_BLOCK_TYPE "AUTO"
#define MAIN_SOC_ONCHIP_MEM_FOR_TILES_INIT_CONTENTS_FILE "final_soc_Main_Soc_onchip_mem_for_Tiles"
#define MAIN_SOC_ONCHIP_MEM_FOR_TILES_INIT_MEM_CONTENT 1
#define MAIN_SOC_ONCHIP_MEM_FOR_TILES_INSTANCE_ID "NONE"
#define MAIN_SOC_ONCHIP_MEM_FOR_TILES_IRQ -1
#define MAIN_SOC_ONCHIP_MEM_FOR_TILES_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MAIN_SOC_ONCHIP_MEM_FOR_TILES_NAME "/dev/Main_Soc_onchip_mem_for_Tiles"
#define MAIN_SOC_ONCHIP_MEM_FOR_TILES_NON_DEFAULT_INIT_FILE_ENABLED 0
#define MAIN_SOC_ONCHIP_MEM_FOR_TILES_RAM_BLOCK_TYPE "AUTO"
#define MAIN_SOC_ONCHIP_MEM_FOR_TILES_READ_DURING_WRITE_MODE "DONT_CARE"
#define MAIN_SOC_ONCHIP_MEM_FOR_TILES_SINGLE_CLOCK_OP 0
#define MAIN_SOC_ONCHIP_MEM_FOR_TILES_SIZE_MULTIPLE 1
#define MAIN_SOC_ONCHIP_MEM_FOR_TILES_SIZE_VALUE 16384
#define MAIN_SOC_ONCHIP_MEM_FOR_TILES_SPAN 16384
#define MAIN_SOC_ONCHIP_MEM_FOR_TILES_TYPE "altera_avalon_onchip_memory2"
#define MAIN_SOC_ONCHIP_MEM_FOR_TILES_WRITABLE 1


/*
 * Main_jtag_uart configuration
 *
 */

#define ALT_MODULE_CLASS_Main_jtag_uart altera_avalon_jtag_uart
#define MAIN_JTAG_UART_BASE 0x150d0
#define MAIN_JTAG_UART_IRQ 5
#define MAIN_JTAG_UART_IRQ_INTERRUPT_CONTROLLER_ID 0
#define MAIN_JTAG_UART_NAME "/dev/Main_jtag_uart"
#define MAIN_JTAG_UART_READ_DEPTH 64
#define MAIN_JTAG_UART_READ_THRESHOLD 8
#define MAIN_JTAG_UART_SPAN 8
#define MAIN_JTAG_UART_TYPE "altera_avalon_jtag_uart"
#define MAIN_JTAG_UART_WRITE_DEPTH 64
#define MAIN_JTAG_UART_WRITE_THRESHOLD 8


/*
 * Main_onchip_mem configuration
 *
 */

#define ALT_MODULE_CLASS_Main_onchip_mem altera_avalon_onchip_memory2
#define MAIN_ONCHIP_MEM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define MAIN_ONCHIP_MEM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define MAIN_ONCHIP_MEM_BASE 0x20000
#define MAIN_ONCHIP_MEM_CONTENTS_INFO ""
#define MAIN_ONCHIP_MEM_DUAL_PORT 1
#define MAIN_ONCHIP_MEM_GUI_RAM_BLOCK_TYPE "AUTO"
#define MAIN_ONCHIP_MEM_INIT_CONTENTS_FILE "final_soc_Main_onchip_mem"
#define MAIN_ONCHIP_MEM_INIT_MEM_CONTENT 1
#define MAIN_ONCHIP_MEM_INSTANCE_ID "NONE"
#define MAIN_ONCHIP_MEM_IRQ -1
#define MAIN_ONCHIP_MEM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MAIN_ONCHIP_MEM_NAME "/dev/Main_onchip_mem"
#define MAIN_ONCHIP_MEM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define MAIN_ONCHIP_MEM_RAM_BLOCK_TYPE "AUTO"
#define MAIN_ONCHIP_MEM_READ_DURING_WRITE_MODE "DONT_CARE"
#define MAIN_ONCHIP_MEM_SINGLE_CLOCK_OP 1
#define MAIN_ONCHIP_MEM_SIZE_MULTIPLE 1
#define MAIN_ONCHIP_MEM_SIZE_VALUE 65536
#define MAIN_ONCHIP_MEM_SPAN 65536
#define MAIN_ONCHIP_MEM_TYPE "altera_avalon_onchip_memory2"
#define MAIN_ONCHIP_MEM_WRITABLE 1


/*
 * Main_sys_id configuration
 *
 */

#define ALT_MODULE_CLASS_Main_sys_id altera_avalon_sysid_qsys
#define MAIN_SYS_ID_BASE 0x15018
#define MAIN_SYS_ID_ID 0
#define MAIN_SYS_ID_IRQ -1
#define MAIN_SYS_ID_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MAIN_SYS_ID_NAME "/dev/Main_sys_id"
#define MAIN_SYS_ID_SPAN 8
#define MAIN_SYS_ID_TIMESTAMP 1641211182
#define MAIN_SYS_ID_TYPE "altera_avalon_sysid_qsys"


/*
 * Mem_for_Game_Data configuration
 *
 */

#define ALT_MODULE_CLASS_Mem_for_Game_Data altera_avalon_onchip_memory2
#define MEM_FOR_GAME_DATA_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define MEM_FOR_GAME_DATA_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define MEM_FOR_GAME_DATA_BASE 0x10000
#define MEM_FOR_GAME_DATA_CONTENTS_INFO ""
#define MEM_FOR_GAME_DATA_DUAL_PORT 1
#define MEM_FOR_GAME_DATA_GUI_RAM_BLOCK_TYPE "M9K"
#define MEM_FOR_GAME_DATA_INIT_CONTENTS_FILE "final_soc_Mem_for_Game_Data"
#define MEM_FOR_GAME_DATA_INIT_MEM_CONTENT 1
#define MEM_FOR_GAME_DATA_INSTANCE_ID "NONE"
#define MEM_FOR_GAME_DATA_IRQ -1
#define MEM_FOR_GAME_DATA_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MEM_FOR_GAME_DATA_NAME "/dev/Mem_for_Game_Data"
#define MEM_FOR_GAME_DATA_NON_DEFAULT_INIT_FILE_ENABLED 0
#define MEM_FOR_GAME_DATA_RAM_BLOCK_TYPE "M9K"
#define MEM_FOR_GAME_DATA_READ_DURING_WRITE_MODE "DONT_CARE"
#define MEM_FOR_GAME_DATA_SINGLE_CLOCK_OP 1
#define MEM_FOR_GAME_DATA_SIZE_MULTIPLE 1
#define MEM_FOR_GAME_DATA_SIZE_VALUE 16384
#define MEM_FOR_GAME_DATA_SPAN 16384
#define MEM_FOR_GAME_DATA_TYPE "altera_avalon_onchip_memory2"
#define MEM_FOR_GAME_DATA_WRITABLE 1


/*
 * Player_Controller configuration
 *
 */

#define ALT_MODULE_CLASS_Player_Controller Player_Controller
#define PLAYER_CONTROLLER_BASE 0x0
#define PLAYER_CONTROLLER_IRQ -1
#define PLAYER_CONTROLLER_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PLAYER_CONTROLLER_NAME "/dev/Player_Controller"
#define PLAYER_CONTROLLER_SPAN 1024
#define PLAYER_CONTROLLER_TYPE "Player_Controller"


/*
 * SRAM_DUAL_CLOCK_100MHz configuration
 *
 */

#define ALT_MODULE_CLASS_SRAM_DUAL_CLOCK_100MHz altpll
#define SRAM_DUAL_CLOCK_100MHZ_BASE 0x150c0
#define SRAM_DUAL_CLOCK_100MHZ_IRQ -1
#define SRAM_DUAL_CLOCK_100MHZ_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SRAM_DUAL_CLOCK_100MHZ_NAME "/dev/SRAM_DUAL_CLOCK_100MHz"
#define SRAM_DUAL_CLOCK_100MHZ_SPAN 16
#define SRAM_DUAL_CLOCK_100MHZ_TYPE "altpll"


/*
 * SRAM_dual_controller_0 configuration
 *
 */

#define ALT_MODULE_CLASS_SRAM_dual_controller_0 SRAM_dual_controller
#define SRAM_DUAL_CONTROLLER_0_BASE 0x400000
#define SRAM_DUAL_CONTROLLER_0_IRQ -1
#define SRAM_DUAL_CONTROLLER_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SRAM_DUAL_CONTROLLER_0_NAME "/dev/SRAM_dual_controller_0"
#define SRAM_DUAL_CONTROLLER_0_SPAN 2097152
#define SRAM_DUAL_CONTROLLER_0_TYPE "SRAM_dual_controller"


/*
 * SRAM_dual_controller_0 configuration as viewed by sgdma_0_m_write
 *
 */

#define SGDMA_0_M_WRITE_SRAM_DUAL_CONTROLLER_0_BASE 0x400000
#define SGDMA_0_M_WRITE_SRAM_DUAL_CONTROLLER_0_IRQ -1
#define SGDMA_0_M_WRITE_SRAM_DUAL_CONTROLLER_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SGDMA_0_M_WRITE_SRAM_DUAL_CONTROLLER_0_NAME "/dev/SRAM_dual_controller_0"
#define SGDMA_0_M_WRITE_SRAM_DUAL_CONTROLLER_0_SPAN 2097152
#define SGDMA_0_M_WRITE_SRAM_DUAL_CONTROLLER_0_TYPE "SRAM_dual_controller"


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "Cyclone IV E"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/Main_jtag_uart"
#define ALT_STDERR_BASE 0x150d0
#define ALT_STDERR_DEV Main_jtag_uart
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/Main_jtag_uart"
#define ALT_STDIN_BASE 0x150d0
#define ALT_STDIN_DEV Main_jtag_uart
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/Main_jtag_uart"
#define ALT_STDOUT_BASE 0x150d0
#define ALT_STDOUT_DEV Main_jtag_uart
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "final_soc"


/*
 * hal configuration
 *
 */

#define ALT_INCLUDE_INSTRUCTION_RELATED_EXCEPTION_API
#define ALT_MAX_FD 32
#define ALT_SYS_CLK none
#define ALT_TIMESTAMP_CLK none


/*
 * keycode_mem configuration
 *
 */

#define ALT_MODULE_CLASS_keycode_mem altera_avalon_onchip_memory2
#define KEYCODE_MEM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define KEYCODE_MEM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define KEYCODE_MEM_BASE 0x15010
#define KEYCODE_MEM_CONTENTS_INFO ""
#define KEYCODE_MEM_DUAL_PORT 1
#define KEYCODE_MEM_GUI_RAM_BLOCK_TYPE "AUTO"
#define KEYCODE_MEM_INIT_CONTENTS_FILE "final_soc_keycode_mem"
#define KEYCODE_MEM_INIT_MEM_CONTENT 1
#define KEYCODE_MEM_INSTANCE_ID "NONE"
#define KEYCODE_MEM_IRQ -1
#define KEYCODE_MEM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define KEYCODE_MEM_NAME "/dev/keycode_mem"
#define KEYCODE_MEM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define KEYCODE_MEM_RAM_BLOCK_TYPE "AUTO"
#define KEYCODE_MEM_READ_DURING_WRITE_MODE "DONT_CARE"
#define KEYCODE_MEM_SINGLE_CLOCK_OP 1
#define KEYCODE_MEM_SIZE_MULTIPLE 1
#define KEYCODE_MEM_SIZE_VALUE 4
#define KEYCODE_MEM_SPAN 4
#define KEYCODE_MEM_TYPE "altera_avalon_onchip_memory2"
#define KEYCODE_MEM_WRITABLE 1


/*
 * resource_sdram configuration
 *
 */

#define ALT_MODULE_CLASS_resource_sdram altera_avalon_new_sdram_controller
#define RESOURCE_SDRAM_BASE 0x10000000
#define RESOURCE_SDRAM_CAS_LATENCY 3
#define RESOURCE_SDRAM_CONTENTS_INFO
#define RESOURCE_SDRAM_INIT_NOP_DELAY 0.0
#define RESOURCE_SDRAM_INIT_REFRESH_COMMANDS 2
#define RESOURCE_SDRAM_IRQ -1
#define RESOURCE_SDRAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define RESOURCE_SDRAM_IS_INITIALIZED 1
#define RESOURCE_SDRAM_NAME "/dev/resource_sdram"
#define RESOURCE_SDRAM_POWERUP_DELAY 200.0
#define RESOURCE_SDRAM_REFRESH_PERIOD 7.8125
#define RESOURCE_SDRAM_REGISTER_DATA_IN 1
#define RESOURCE_SDRAM_SDRAM_ADDR_WIDTH 0x19
#define RESOURCE_SDRAM_SDRAM_BANK_WIDTH 2
#define RESOURCE_SDRAM_SDRAM_COL_WIDTH 10
#define RESOURCE_SDRAM_SDRAM_DATA_WIDTH 32
#define RESOURCE_SDRAM_SDRAM_NUM_BANKS 4
#define RESOURCE_SDRAM_SDRAM_NUM_CHIPSELECTS 1
#define RESOURCE_SDRAM_SDRAM_ROW_WIDTH 13
#define RESOURCE_SDRAM_SHARED_DATA 0
#define RESOURCE_SDRAM_SIM_MODEL_BASE 0
#define RESOURCE_SDRAM_SPAN 134217728
#define RESOURCE_SDRAM_STARVATION_INDICATOR 0
#define RESOURCE_SDRAM_TRISTATE_BRIDGE_SLAVE ""
#define RESOURCE_SDRAM_TYPE "altera_avalon_new_sdram_controller"
#define RESOURCE_SDRAM_T_AC 5.5
#define RESOURCE_SDRAM_T_MRD 3
#define RESOURCE_SDRAM_T_RCD 20.0
#define RESOURCE_SDRAM_T_RFC 70.0
#define RESOURCE_SDRAM_T_RP 20.0
#define RESOURCE_SDRAM_T_WR 14.0


/*
 * resource_sdram configuration as viewed by sgdma_0_m_read
 *
 */

#define SGDMA_0_M_READ_RESOURCE_SDRAM_BASE 0x10000000
#define SGDMA_0_M_READ_RESOURCE_SDRAM_CAS_LATENCY 3
#define SGDMA_0_M_READ_RESOURCE_SDRAM_CONTENTS_INFO
#define SGDMA_0_M_READ_RESOURCE_SDRAM_INIT_NOP_DELAY 0.0
#define SGDMA_0_M_READ_RESOURCE_SDRAM_INIT_REFRESH_COMMANDS 2
#define SGDMA_0_M_READ_RESOURCE_SDRAM_IRQ -1
#define SGDMA_0_M_READ_RESOURCE_SDRAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SGDMA_0_M_READ_RESOURCE_SDRAM_IS_INITIALIZED 1
#define SGDMA_0_M_READ_RESOURCE_SDRAM_NAME "/dev/resource_sdram"
#define SGDMA_0_M_READ_RESOURCE_SDRAM_POWERUP_DELAY 200.0
#define SGDMA_0_M_READ_RESOURCE_SDRAM_REFRESH_PERIOD 7.8125
#define SGDMA_0_M_READ_RESOURCE_SDRAM_REGISTER_DATA_IN 1
#define SGDMA_0_M_READ_RESOURCE_SDRAM_SDRAM_ADDR_WIDTH 0x19
#define SGDMA_0_M_READ_RESOURCE_SDRAM_SDRAM_BANK_WIDTH 2
#define SGDMA_0_M_READ_RESOURCE_SDRAM_SDRAM_COL_WIDTH 10
#define SGDMA_0_M_READ_RESOURCE_SDRAM_SDRAM_DATA_WIDTH 32
#define SGDMA_0_M_READ_RESOURCE_SDRAM_SDRAM_NUM_BANKS 4
#define SGDMA_0_M_READ_RESOURCE_SDRAM_SDRAM_NUM_CHIPSELECTS 1
#define SGDMA_0_M_READ_RESOURCE_SDRAM_SDRAM_ROW_WIDTH 13
#define SGDMA_0_M_READ_RESOURCE_SDRAM_SHARED_DATA 0
#define SGDMA_0_M_READ_RESOURCE_SDRAM_SIM_MODEL_BASE 0
#define SGDMA_0_M_READ_RESOURCE_SDRAM_SPAN 134217728
#define SGDMA_0_M_READ_RESOURCE_SDRAM_STARVATION_INDICATOR 0
#define SGDMA_0_M_READ_RESOURCE_SDRAM_TRISTATE_BRIDGE_SLAVE ""
#define SGDMA_0_M_READ_RESOURCE_SDRAM_TYPE "altera_avalon_new_sdram_controller"
#define SGDMA_0_M_READ_RESOURCE_SDRAM_T_AC 5.5
#define SGDMA_0_M_READ_RESOURCE_SDRAM_T_MRD 3
#define SGDMA_0_M_READ_RESOURCE_SDRAM_T_RCD 20.0
#define SGDMA_0_M_READ_RESOURCE_SDRAM_T_RFC 70.0
#define SGDMA_0_M_READ_RESOURCE_SDRAM_T_RP 20.0
#define SGDMA_0_M_READ_RESOURCE_SDRAM_T_WR 14.0


/*
 * resource_sdram_pll configuration
 *
 */

#define ALT_MODULE_CLASS_resource_sdram_pll altpll
#define RESOURCE_SDRAM_PLL_BASE 0x15030
#define RESOURCE_SDRAM_PLL_IRQ -1
#define RESOURCE_SDRAM_PLL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define RESOURCE_SDRAM_PLL_NAME "/dev/resource_sdram_pll"
#define RESOURCE_SDRAM_PLL_SPAN 16
#define RESOURCE_SDRAM_PLL_TYPE "altpll"


/*
 * sgdma_0 configuration
 *
 */

#define ALT_MODULE_CLASS_sgdma_0 altera_avalon_sgdma
#define SGDMA_0_ADDRESS_WIDTH 32
#define SGDMA_0_ALWAYS_DO_MAX_BURST 1
#define SGDMA_0_ATLANTIC_CHANNEL_DATA_WIDTH 4
#define SGDMA_0_AVALON_MM_BYTE_REORDER_MODE 0
#define SGDMA_0_BASE 0x15080
#define SGDMA_0_BURST_DATA_WIDTH 8
#define SGDMA_0_BURST_TRANSFER 0
#define SGDMA_0_BYTES_TO_TRANSFER_DATA_WIDTH 16
#define SGDMA_0_CHAIN_WRITEBACK_DATA_WIDTH 32
#define SGDMA_0_COMMAND_FIFO_DATA_WIDTH 104
#define SGDMA_0_CONTROL_DATA_WIDTH 8
#define SGDMA_0_CONTROL_SLAVE_ADDRESS_WIDTH 0x4
#define SGDMA_0_CONTROL_SLAVE_DATA_WIDTH 32
#define SGDMA_0_DESCRIPTOR_READ_BURST 0
#define SGDMA_0_DESC_DATA_WIDTH 32
#define SGDMA_0_HAS_READ_BLOCK 1
#define SGDMA_0_HAS_WRITE_BLOCK 1
#define SGDMA_0_IN_ERROR_WIDTH 0
#define SGDMA_0_IRQ 0
#define SGDMA_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SGDMA_0_NAME "/dev/sgdma_0"
#define SGDMA_0_OUT_ERROR_WIDTH 0
#define SGDMA_0_READ_BLOCK_DATA_WIDTH 32
#define SGDMA_0_READ_BURSTCOUNT_WIDTH 4
#define SGDMA_0_SPAN 64
#define SGDMA_0_STATUS_TOKEN_DATA_WIDTH 24
#define SGDMA_0_STREAM_DATA_WIDTH 32
#define SGDMA_0_TYPE "altera_avalon_sgdma"
#define SGDMA_0_UNALIGNED_TRANSFER 1
#define SGDMA_0_WRITE_BLOCK_DATA_WIDTH 32
#define SGDMA_0_WRITE_BURSTCOUNT_WIDTH 4

#endif /* __SYSTEM_H_ */
